name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint SQL
        run: |
          find . -name '*.sql' -print0 | xargs -0 -n 1 sqlfluff lint --dialect ansi || true
      - name: Run tests
        run: python -m pytest -v
